# Generated by Django 2.2.1 on 2019-06-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
